<a href="https://colab.research.google.com/github/shrishtikala/practice/blob/master/data_eng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
#reading csv file from url
df=pd.read_csv('http://13.234.66.67/summer19/datasets/info.csv')

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [0]:
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [0]:
#to avoid/remove header
X=df.iloc[:,0:].values
X

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
# removing missing value and replacing it with some relevant data
#df.describe()
from sklearn.preprocessing import Imputer

In [0]:
#axis =0 check column orientedd
# tor replace that data of nan with mean max min etccc through strategy
imp=Imputer(missing_values='NaN',axis=0,strategy='mean')

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
impute=imp.fit(X[:,1:3])        # this is only fitting of columns that we want to process
#that column which we want to work on

In [0]:
#  time for transforming the fitted columns 
# to find the original x and replace it with the mean
# replace it at same p,ace
X[:,1:3]=impute.transform(X[:,1:3])
X

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, 63777.77777777778, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', 38.77777777777778, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
#to assign string value with integer or float value like bumpy 0 and smooth 1
from sklearn.preprocessing import LabelEncoder

In [0]:
cont=LabelEncoder()       # this is for country labelling

In [0]:
#now applying column 1st in this laabel encoder
X[:,0]=cont.fit_transform(X[:,0])

In [0]:
X      # by comparision we found 0-france spain- 2 germany- 1

array([[0, 44.0, 72000.0, 'No'],
       [2, 27.0, 48000.0, 'Yes'],
       [1, 30.0, 54000.0, 'No'],
       [2, 38.0, 61000.0, 'No'],
       [1, 40.0, 63777.77777777778, 'Yes'],
       [0, 35.0, 58000.0, 'Yes'],
       [2, 38.77777777777778, 52000.0, 'No'],
       [0, 48.0, 79000.0, 'Yes'],
       [1, 50.0, 83000.0, 'No'],
       [0, 37.0, 67000.0, 'Yes']], dtype=object)

In [0]:
# labelling last column
p=LabelEncoder()



In [0]:
X[:,3]=p.fit_transform(X[:,3])

In [0]:
X

array([[0, 44.0, 72000.0, 0],
       [2, 27.0, 48000.0, 1],
       [1, 30.0, 54000.0, 0],
       [2, 38.0, 61000.0, 0],
       [1, 40.0, 63777.77777777778, 1],
       [0, 35.0, 58000.0, 1],
       [2, 38.77777777777778, 52000.0, 0],
       [0, 48.0, 79000.0, 1],
       [1, 50.0, 83000.0, 0],
       [0, 37.0, 67000.0, 1]], dtype=object)

In [0]:
# through this we got to know that 0 and 2 have much difference and therefore we cant do this with distance formula form or knn
# therefore we use dummy variable

In [0]:
#now encoding first columnnn  making subcolumn of first column
#ecodig
from sklearn.preprocessing import OneHotEncoder


In [0]:
#feature 0 where you want to do this work
firstcl=OneHotEncoder(categorical_features=[0])       # identifining and defining one exact no. where we want to make category



In [0]:
X=firstcl.fit_transform(X).toarray()          # after transforming we need to convert into numpy array

In [0]:
X.astype(int)

array([[    1,     0,     0,    44, 72000,     0],
       [    0,     0,     1,    27, 48000,     1],
       [    0,     1,     0,    30, 54000,     0],
       [    0,     0,     1,    38, 61000,     0],
       [    0,     1,     0,    40, 63777,     1],
       [    1,     0,     0,    35, 58000,     1],
       [    0,     0,     1,    38, 52000,     0],
       [    1,     0,     0,    48, 79000,     1],
       [    0,     1,     0,    50, 83000,     0],
       [    1,     0,     0,    37, 67000,     1]])